### ISSUE TITLE
FEATURE: Calculate should exclude restricted items

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#1]
Hello,

to prevent moving containers (any plastic wrap) they should be notified with error that they are trying to move containers which are forbidden (might be as a setting). MTUs, 

On screenshot is filter in EVE which is excluding those items (not all of them tho)

![Screenshot 2023-02-02 at 11 23 35](https://user-images.githubusercontent.com/46750448/216299038-3e4f62c8-376e-428a-8a35-443a57cf9dc7.png)

**Comment by recursivetree** [comment]
It makes sense to not allow containers, but why no MTUs? As far as I know, they can't act a a container while in the inventory.

**Comment by martinskalicky** [comment]
You are right. It's basically just containers.

**Comment by recursivetree** [comment]
should be fixed
