### ISSUE TITLE
FEATURE: Add "Next" button

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#15]
It would be great to have button when u receive calculation for "next" calculation.

When you are doing more courier contracts it could be very handy to just click button and start new calculation rather then finding it in menu.

Just a life-hack nothing big. It would make it more easier to use.

**Comment by recursivetree** [comment]
Makes sense. For now, you can just use the back function of the browser

**Comment by recursivetree** [comment]
added, will come with the next release
