### ISSUE TITLE
FEATURE: Colors - visuals

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#16]
Might be cool to have reward green and collateral red as we have same colors in the game (calculation)

**Comment by recursivetree** [comment]
I'll take a look at it

**Comment by recursivetree** [comment]
if you want to take some work of me, please send a screenshoot

**Comment by martinskalicky** [comment]
![Screenshot 2023-02-19 at 14 29 54](https://user-images.githubusercontent.com/46750448/219951323-fe2d92e7-e279-46fe-aac0-42ab0bbf2dd6.png)

**Comment by martinskalicky** [comment]
![Screenshot 2023-02-19 at 14 30 54](https://user-images.githubusercontent.com/46750448/219951402-a5bc9eac-0cbd-4599-b7d1-3d6eb89aae0d.png)

**Comment by recursivetree** [comment]
added, will come with the next release
