### ISSUE TITLE
BUG: Wrong collateral + reward

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#17]
""
Alloyed Tritanium Bar	7	Salvaged Materials			0.07 m3	53 751.88 ISK
Angel Standard Trigger Mechanism	1	Artifacts and Prototypes			0.10 m3	42 791.80 ISK
ATXVIII 1v1 Battleships Proving Filament	1	Abyssal Proving Filaments			0.10 m3	
Blood Silver Tag	2	Criminal Tags			0.20 m3	320 259.52 ISK
Border-5 'Pochven' Filament	1	Triglavian Space Filaments			0.10 m3	746 030.03 ISK
Broken Drone Transceiver	26	Salvaged Materials			0.26 m3	261 590.68 ISK
""

returns
![Screenshot 2023-03-04 at 14 17 40](https://user-images.githubusercontent.com/46750448/222904048-3b4ffa0f-65c5-4674-b71e-234cf083cca1.png)

**Comment by martinskalicky** [comment]
Might be good to throw an warning if wrong (unexpected) parsing happens. Something like "use icon mode in EVE before you parse" or something like that

**Comment by recursivetree** [comment]
I have to look into why this happens. My guess is that for example `ATXVIII 1v1 Battleships Proving Filament` is not in the sde and therefore not recognised

**Comment by recursivetree** [comment]
I got it. for some reason, you have the ISK numbers formatted using a space instead of a tab character like in my client. Is this maybe language dependent?

**Comment by recursivetree** [comment]
Should be fixed in treelib 1.1.3
