### ISSUE TITLE
BUG : ERROR 500 after update

### ISSUE THREAD

**Issue by Erkaek** [recursivetree/seat-transport#18]
Hey :)

i'v an error 500 after the last update :/ 

![Capture d’écran 2023-03-04 142040](https://user-images.githubusercontent.com/80131775/222904162-27e100aa-6daa-4cc6-ae0b-12f8b7e1a828.png)

**Comment by martinskalicky** [comment]
@Erkaek Do u have TreeLib updated to latest version?

**Comment by Erkaek** [comment]
yep v1.1.2

**Comment by martinskalicky** [comment]
@Erkaek Facing same issue. So upvote from me.

**Comment by recursivetree** [comment]
should be fixed with treelib 1.1.3. Just restart you stack and it will install the latest version of treelib, even if seat-transport didn't change
