### ISSUE TITLE
BUG/FEATURE - Settings/Input is not stored when hitting "back" button

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#19]
Hello,

before latest update "back" button after calculation stored route and items inside the window. This was used when creating multiple contracts.

Can we get it back? 

Right now hitting "back" button is reseting the path and items.

**Comment by recursivetree** [comment]
The back button was only added in the last version. Are you talking about pressing back in the browser controls?

**Comment by martinskalicky** [comment]
Yes, sorry my language skills are sleeping.

Yes, back button is new. However it does not stores values. The website back button works still well tho. Just people were starting using the button and thats why we have this.

**Comment by recursivetree** [comment]
The route is now persistent when using the back button. Are you sure you want to have the items too when you use the back button?

**Comment by martinskalicky** [comment]
Yes, items should be there too.

**Comment by recursivetree** [comment]
this will come with the next release
