### ISSUE TITLE
FEATURE: Set maximum m3 which u can move

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#2]
Hello,

its really critical to be able to set maximum m3 which we are able to move. I believe this could be settings.

To make this super uber cool. If settings could be attached to route its GOLDEN! Cause in HS u will be able to move more m3 then when u are using JF or BR (DST)

Martin

**Comment by recursivetree** [comment]
Sure, that is a useful feature.

**Comment by recursivetree** [comment]
do you have a reasonable default for this?

**Comment by recursivetree** [comment]
added

**Comment by martinskalicky** [comment]
Default is hard to set, because each JF has different m3
