### ISSUE TITLE
FEATURE: Change units in MAX COLLATERAL in settings

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#20]
Hello,

this is quality of life improvement. Would be cool if default unit there would be bilion ISKs not just ISKS.
![Screenshot 2023-03-13 at 19 13 57](https://user-images.githubusercontent.com/46750448/224792156-a79c92c8-6654-4d98-aa71-963b1c020d32.png)

**Comment by recursivetree** [comment]
You should need to change these setting so rarely that it doesn't matter
