### ISSUE TITLE
BUG: Receiving 500 server error when I try to calculate

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#22]
Hello,

I do get server error 500 when I try to calculate anything.

Steps to reproduce:

1. Define any way to go
2. Select some items in the game and paste them to the calculate section
3. Server error 500

**Comment by recursivetree** [comment]
can you either provide a screenshoot of your settings and the exact items you used, or enable debug mode to show the error that occured?

**Comment by martinskalicky** [comment]
![Screenshot 2023-11-19 at 19 48 58](https://github.com/recursivetree/seat-transport/assets/46750448/321fe951-1d2e-4585-9d81-f13843bf62a0)
![Screenshot 2023-11-19 at 19 48 48](https://github.com/recursivetree/seat-transport/assets/46750448/1237f8b7-600d-4468-95c6-96f085ab9788)

**Comment by martinskalicky** [comment]
![Screenshot 2023-11-19 at 19 49 30](https://github.com/recursivetree/seat-transport/assets/46750448/54991fb8-3d77-42c4-8932-461244ae1514)

**Comment by recursivetree** [comment]
Enable the debug mode or look at the logs and report the error you are encountering.

**Comment by Maxos-programming** [comment]
![image](https://github.com/recursivetree/seat-transport/assets/24267779/28b3e54a-d4ec-4053-8631-e8109f71f15d)
Thats the Error behind i think so.

It can be reproduced by a fresh installation

**Comment by recursivetree** [comment]
A 500 error means internal server error in general, it is most likely not the same error. Are you on a docker or bare install? In any case, you need to force-update your sde

**Comment by Maxos-programming** [comment]
SDE Redownloaded and now:
![image](https://github.com/recursivetree/seat-transport/assets/24267779/c506534a-492f-4128-b966-6a9dd569a067)
After a litte bit Debug i found out its a Null error because the item not foundable over the given ID

PS: Bare Install

**Comment by martinskalicky** [comment]
> SDE Redownloaded and now:
> 
> ![image](https://github.com/recursivetree/seat-transport/assets/24267779/c506534a-492f-4128-b966-6a9dd569a067)
> 
> After a litte bit Debug i found out its a Null error because the item not foundable over the given ID
> 
> 
> 
> PS: Bare Install

Exactly same for me.

**Comment by recursivetree** [comment]
Are you guys on SeAT 5?

**Comment by recursivetree** [comment]
It should be possible to resolve this issue by configuring a price provider in the plugin settings.

**Comment by Maxos-programming** [comment]
Yes I'm on SeAT5 already. And no the Price Provider is fine. The null error comes because in the invVolumes the given Id dont exists.

**Comment by Maxos-programming** [comment]
Last Update Fixed it. Thanks

**Comment by recursivetree** [comment]
> Yes I'm on SeAT5 already. And no the Price Provider is fine. The null error comes because in the invVolumes the given Id dont exists.

The null error is not related to invVolumes. The invVolume was another, independent issue. But great to hear you got it working.
