### ISSUE TITLE
FEATURE: Add RUSH option

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#3]
Hello,

ability to set RUSH option in case its critical delivery. This will come with settings (%?) in route how much more expensive it would be.

Each route may have settings 

- RUSH enabled/disabled
- % increase (for m3 and for collat)

When people are selecting route, they might have some tickbox or something if they want to use RUSH. Details about that we might add to info that would be enough.

Martin

**Comment by recursivetree** [comment]
I can do that, yes

**Comment by recursivetree** [comment]
added
