### ISSUE TITLE
FEATURE: Add "Availability"

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#5]
Hello

It should describe to who they should contract it (Private and Name) or "My Corporation") so its clear even for newbies.
![Screenshot 2023-02-02 at 11 29 33](https://user-images.githubusercontent.com/46750448/216301482-9d0211d1-a6d7-4d12-aa9e-bae03fbbc0ce.png)

Martin

**Comment by recursivetree** [comment]
That's the thing you write in the info text. I don't really see a need to have a feature in the plugin specific for this. Using the info text, you can customize it way more towards the needs of your corporation

**Comment by martinskalicky** [comment]
I see. You can do info text which is general and it will be for visible for any route the same text.

All routes might not be serviced by one corporation (characters). Thats exactly our use-case where some routes are not managed by our group but by external provider.

**Comment by recursivetree** [comment]
would a per-route info text be fine?

**Comment by martinskalicky** [comment]
@recursivetree That would be fantastic!

**Comment by recursivetree** [comment]
added
