### ISSUE TITLE
BUG: Not correct m3

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-transport#7]
Looks like BCS are with wrong m3 settings if u do Prophecy, Drake etc they do count with 50 000m3 (should be 15k m3)
Raven, Rattlesnake etc do count with 15 000m3 (should be 50k m3)

**Comment by martinskalicky** [comment]
![Screenshot 2023-02-02 at 11 54 30](https://user-images.githubusercontent.com/46750448/216305875-01fd369a-533c-49c8-b483-b278cf9f4500.png)


![Screenshot 2023-02-02 at 11 54 42](https://user-images.githubusercontent.com/46750448/216306086-0286ac31-1f0b-43cb-82e7-fb2b75ea580e.png)

**Comment by recursivetree** [comment]
that is indeed wrong, but it isn't an error in the plugin. Instead, the data is wrong in the sde

**Comment by recursivetree** [comment]
I reported it to Steve Ronuken, we'll see if he fixes it. Otherwise we can apply a workaround. But for now, I'll wait and see

**Comment by recursivetree** [comment]
I added a workaround, waiting for Steve to fix it
