### ISSUE TITLE
BUG: Collateral calc issue

### ISSUE THREAD

**Issue by Erkaek** [recursivetree/seat-transport#8]
The collateral is not calculated according to the settings

![image](https://user-images.githubusercontent.com/80131775/216822209-b43dcad0-925c-4d1d-8ce0-13bb6e0bb68e.png)
![image](https://user-images.githubusercontent.com/80131775/216822229-46ff7be1-56bd-4bbc-b567-2457a0153302.png)

**Comment by martinskalicky** [comment]
This is duplicate of #7. @Erkaek You can find answers there.

**Comment by Erkaek** [comment]
it's not the same issue
here it's a problem in the calculation of the collateral, i'v set it to 0% but a collateral is show and i'v try with other percentage and it don't change anything

**Comment by Erkaek** [comment]
> This is duplicate of #7. @Erkaek You can find answers there.

it's not the same issue
here it's a problem in the calculation of the collateral, i'v set it to 0% but a collateral is show and i'v try with other percentage and it don't change anything

**Comment by Erkaek** [comment]
> This is duplicate of #7. @Erkaek You can find answers there.

it's not the same issue
here it's a problem in the calculation of the collateral, i'v set it to 0% but a collateral is show and i'v try with other percentage and it don't change anything

**Comment by recursivetree** [comment]
can you please include the items you use as an input?

**Comment by recursivetree** [comment]
actually, I know what's happening. collateral shows the value of your items, reward collateral % is the influence of the collateral on the reward. Therefore, the calculations are correct, `339700000*0 + 800*15000=12000000`
